### ISSUE TITLE
perf/accuracy test for sift.cpp

### ISSUE THREAD

**Issue by Yosshi999** [terfendail/opencv#1]
- [x] Find reasonably big / small images and add them to the existing perf test of sift
- [x] Create the accuracy test which check if sift always creates same keypoints/descriptors, and put those files to opencv_extra repository

**Comment by Yosshi999** [comment]
I found the test named feature2d_(detect|extract|detectAndExtract) in [perf_features2d](https://github.com/opencv/opencv/blob/master/modules/features2d/perf/perf_feature2d.hpp) , and it is for testing modules except SIFT with 3 images; leuven/img1.png, a3.png, s2.jpg.
Two in those images are already tested in [perf_sift.cpp](https://github.com/opencv/opencv/blob/master/modules/features2d/perf/perf_sift.cpp) and the rest(s2.jpg) is larger than two, so I think merging this test into perf_features2d is the best solution for the first task.

**Comment by Yosshi999** [comment]
MEMO: regression test for sift descriptor
https://github.com/opencv/opencv/blob/master/modules/features2d/test/test_descriptors_regression.impl.hpp#L72
https://github.com/opencv/opencv_extra/blob/master/testdata/cv/features2d/descriptor_extractors/descriptor-sift

**Comment by terfendail** [comment]
Could you please also check performance for `opencv_extra\testdata\perf\1920x1080.png`
and `opencv_extra\testdata\stitching\boat1.jpg` to investigate how size and content of image affect execution time? This information could help to decide whether it is necessary to extend the test set with FullHD or higher resolution images

**Comment by Yosshi999** [comment]
(millisecond) | mean | median | min | samples 
-- | -- | -- | -- | -- 
(SIFT_DEFAULT,   "cv/.../leuven/img1.png") (900x600) | 168 | 168 | 166 | 13 
(SIFT_DEFAULT,   "stitching/a3.png") (600x768) | 157 | 157 | 157 | 10 
(SIFT_DEFAULT,   "stitching/s2.jpg") (1385x700)| 346 | 345| 341| 10 
(SIFT_DEFAULT,   "perf/1920x1080.png") | 547| 546 | 542 | 10 
(SIFT_DEFAULT,   "stitching/boat1.jpg") (3888x2592) | 2571| 2570 | 2554 | 13 

```
Parallel framework: pthreads (nthreads=2)
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
Intel(R) IPP version: ippIP AVX2 (l9) 2020.0.0 Gold (-) Oct 19 2019
OpenCL is disabled
```
on two Intel(R) Xeon(R) CPU @ 2.20GHz

**Comment by Yosshi999** [comment]
It seems that the execution time is increasing linearly w.r.t. the number of pixels.

**Comment by terfendail** [comment]
There is a constant overhead of 50, but anyway I agree `s2.jpg` is of reasonable size

**Comment by Yosshi999** [comment]
disabled test:
https://github.com/opencv/opencv/blob/master/modules/features2d/test/test_descriptors_invariance.cpp#L40

https://github.com/opencv/opencv/blob/master/modules/features2d/test/test_detectors_invariance.cpp#L40

**Comment by Yosshi999** [comment]
~- [ ] ↑ investigate these failed tests and make them passed in the main repository~
Moved to #3

**Comment by Yosshi999** [comment]
```
$ OPENCV_CPU_DISABLE=AVX2 ./opencv_test_features2d --gtest_filter=SIFT/DetectorScaleInvariance.*
...
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2? *AVX512-SKX?
...
scale = 1.5, keyPointMatchesRatio = 0.725973, scaleInliersRatio = 0.99606
scale = 2, keyPointMatchesRatio = 0.769883, scaleInliersRatio = 0.998623
/home/yosshi999_for_entry/opencv/modules/features2d/test/test_detectors_invariance.impl.hpp:198: Failure
Expected: (keyPointMatchesRatio) >= (minKeyPointMatchesRatio), actual: 0.598093 vs 0.69

$  ./opencv_test_features2d --gtest_filter=SIFT/DetectorScaleInvariance.*
...
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
...
scale = 1.5, keyPointMatchesRatio = 0.725973, scaleInliersRatio = 0.99606
scale = 2, keyPointMatchesRatio = 0.769883, scaleInliersRatio = 0.998623
/home/yosshi999_for_entry/opencv/modules/features2d/test/test_detectors_invariance.impl.hpp:198: Failure
Expected: (keyPointMatchesRatio) >= (minKeyPointMatchesRatio), actual: 0.598909 vs 0.69
```

**Comment by Yosshi999** [comment]
I think missing [removeVerySmallKeypoints](https://github.com/opencv/opencv_contrib/blob/1248735d1edd863e3b931fd6d0859720f11d3573/modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp#L426) is the reason of these failure.
I will investigate what `octave & 128` means.

after adding `removeVerySmallKeypoints`:
```
$ ./bin/opencv_test_features2d --gtest_filter=SIFT/DetectorScaleInvariance.*
CTEST_FULL_OUTPUT
OpenCV version: 4.3.0-dev
OpenCV VCS version: 4.3.0-312-g2115ba82a2
Build type: Release
Compiler: /usr/bin/c++  (ver 8.3.0)
Parallel framework: pthreads (nthreads=2)
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
Intel(R) IPP version: ippIP AVX2 (l9) 2020.0.0 Gold (-) Oct 19 2019
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
Note: Google Test filter = SIFT/DetectorScaleInvariance.*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SIFT/DetectorScaleInvariance
[ RUN      ] SIFT/DetectorScaleInvariance.scale/0, where GetParam() = ("detectors_descriptors_evaluation/images_datasets/bikes/img1.png", 0.69, 0.98)
scale = 1.5, keyPointMatchesRatio = 0.764919, scaleInliersRatio = 1
scale = 2, keyPointMatchesRatio = 0.875, scaleInliersRatio = 1
scale = 2.5, keyPointMatchesRatio = 0.757463, scaleInliersRatio = 1
[       OK ] SIFT/DetectorScaleInvariance.scale/0 (456 ms)
[----------] 1 test from SIFT/DetectorScaleInvariance (456 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (456 ms total)
[  PASSED  ] 1 test.
```

**Comment by Yosshi999** [comment]
In fact, a lot of keypoints are rejected by this function.

| scale | detected -> after removal |
|--| -- |
| scale = 1 (`keypoints0`) | 3384 -> 978 |
| scale = 1.5 | 1748 -> 553 |
| scale = 2 |  943 -> 360 |
| scale = 2.5 |  733 -> 268 |

**Comment by Yosshi999** [comment]
It seems that there is another reason of the failure for SIFT descriptor.
Thanks to the removal the result gets better, but it still fails.

| scale | descInliersRatio w/o removal | descInliersRatio with removal |
|--|--|--|
| 1.5 | 0.924645 | 0.974438
| 2 | 0.643913 (fail) | 0.848671
| 2.5 | 0.329787 (fail) | 0.595092 (fail)

**Comment by Yosshi999** [comment]
https://github.com/opencv/opencv/pull/17618
