### ISSUE TITLE
Bit-exact GaussianBlur for 16,32-bit integer

### ISSUE THREAD

**Issue by Yosshi999** [terfendail/opencv#16]
In current implementation, it seems that bit-exact gaussian blur only supports CV_8U (https://github.com/terfendail/opencv/blob/3.4/modules/imgproc/src/smooth.dispatch.cpp#L657).
To create precise Gaussian pyramids and DoG in bit-exact SIFT, we need fixpoint gaussian blur.

**Comment by terfendail** [comment]
Merged by [#18167](https://github.com/opencv/opencv/pull/18167)
