### ISSUE TITLE
Prepare a short video report about GSoC2020 experience

### ISSUE THREAD

**Issue by Yosshi999** [terfendail/opencv#19]

**Comment by terfendail** [comment]
[GSoC Student guide](https://google.github.io/gsocguides/student/evaluations#final-evaluations-and-work-product-submission) states that:
> You are required to provide a link to the work you created during your current GSoC participation, in addition to your evaluation. Essentially the target of the link should contain a short description of what work was done, what code got merged, what code didn’t get merged, and what’s left to do.

That looks like a kind of textual final report that also could be added to the last PR as summary of the summer work. And could be a starting point for video.

Video summarizing/demonstrating the results should be of 20-30 seconds to 1 min duration and should be uploaded somewhere like Google drive, dropbox etc. Deadline for videos is unaligned with GSoC schedule and is end of August or 1 week of September.

Overall OpenCV GSoC 2020 "video" report will be made from videos of all projects to put it to OpenCV youtube channel.
For each project some titles with the project name, student and mentor(s) names will be inserted in a uniform way, so it's not necessary to put it in. Complete list of projects will also be provided below the video in text form with the link to pull requests.

Also there is an opportunity to write a post to OpenCV blog to additionally advertise/promote your work. There is no specific deadline for blog post but preferably it should be this fall while the results are fresh.

**Comment by Yosshi999** [comment]
draft of the textual final report:
https://docs.google.com/document/d/10gWapo1yMuTV9XQUS64EOQUycJ3BlasLndlZzZMsy9g/edit?usp=sharing

**Comment by terfendail** [comment]
Report looks fine. The only thing I'd want to discuss is performance results for AVX2 to UI reimplementation. Maybe it make sense to add per architecture results table for a single test(SIFT_DEFAULT, "stitching/s2.jpg") like that

Architecture | detect(pre/post/scale) | compute(pre/post/scale) | detect&compute(pre/post/scale)
--- | --- | --- | ---
SSE | 221.66/218.72/1.013442 | 206.91/180.9/1.143781 | 435.27/397.29/1.095598

Or with just scales

**Comment by Yosshi999** [comment]
I added tables of the benchmarks.

**Comment by Yosshi999** [comment]
video link
https://drive.google.com/file/d/1l2RRpm_O3mKn6PUfZLFSU9Fhu2HT-VaM/view?usp=sharing

**Comment by terfendail** [comment]
@vpisarev Could you please share your thoughts on the report video?
