### ISSUE TITLE
Fix disabled SIFT scale invariance tests on bike image

### ISSUE THREAD

**Issue by terfendail** [terfendail/opencv#3]
In `test_descriptors_invariance.cpp`
DescriptorScaleInvariance(Line 40)
In `test_detectors_invariance.cpp`
DetectorScaleInvariance(Line 40)

**Comment by Yosshi999** [comment]
I think missing [removeVerySmallKeypoints](https://github.com/opencv/opencv_contrib/blob/1248735d1edd863e3b931fd6d0859720f11d3573/modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp#L426) is the reason of these failure.
I will investigate what `octave & 128` means. It seems to be "octave is negative", and the negative octave appears in [retrieving doubled image](https://github.com/opencv/opencv/blob/master/modules/features2d/src/sift.dispatch.cpp#L513).
I'm not sure whether these keypoints are rejected in Lowe's paper.

after adding `removeVerySmallKeypoints`:
```
$ ./bin/opencv_test_features2d --gtest_filter=SIFT/DetectorScaleInvariance.*
CTEST_FULL_OUTPUT
OpenCV version: 4.3.0-dev
OpenCV VCS version: 4.3.0-312-g2115ba82a2
Build type: Release
Compiler: /usr/bin/c++  (ver 8.3.0)
Parallel framework: pthreads (nthreads=2)
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
Intel(R) IPP version: ippIP AVX2 (l9) 2020.0.0 Gold (-) Oct 19 2019
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
Note: Google Test filter = SIFT/DetectorScaleInvariance.*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SIFT/DetectorScaleInvariance
[ RUN      ] SIFT/DetectorScaleInvariance.scale/0, where GetParam() = ("detectors_descriptors_evaluation/images_datasets/bikes/img1.png", 0.69, 0.98)
scale = 1.5, keyPointMatchesRatio = 0.764919, scaleInliersRatio = 1
scale = 2, keyPointMatchesRatio = 0.875, scaleInliersRatio = 1
scale = 2.5, keyPointMatchesRatio = 0.757463, scaleInliersRatio = 1
[       OK ] SIFT/DetectorScaleInvariance.scale/0 (456 ms)
[----------] 1 test from SIFT/DetectorScaleInvariance (456 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (456 ms total)
[  PASSED  ] 1 test.
```

In fact, a lot of keypoints are rejected by this function.

| scale | detected -> after removal |
|--| -- |
| scale = 1 (`keypoints0`) | 3384 -> 978 |
| scale = 1.5 | 1748 -> 553 |
| scale = 2 |  943 -> 360 |
| scale = 2.5 |  733 -> 268 |

However, it seems that there is another reason for the failure of `DescriptorScaleInvariance`.
Thanks to the removal the result gets better, but it still fails.

| scale | descInliersRatio w/o removal | descInliersRatio with removal |
|--|--|--|
| 1.5 | 0.924645 | 0.974438
| 2 | 0.643913 (fail) | 0.848671
| 2.5 | 0.329787 (fail) | 0.595092 (fail)

**Comment by Yosshi999** [comment]
Some AVX2 intrinsics change the robustness of the detector. (It may be just floating point's error?)

```
$ OPENCV_CPU_DISABLE=AVX2 ./opencv_test_features2d --gtest_filter=SIFT/DetectorScaleInvariance.*
...
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2? *AVX512-SKX?
...
scale = 1.5, keyPointMatchesRatio = 0.725973, scaleInliersRatio = 0.99606
scale = 2, keyPointMatchesRatio = 0.769883, scaleInliersRatio = 0.998623
/home/yosshi999_for_entry/opencv/modules/features2d/test/test_detectors_invariance.impl.hpp:198: Failure
Expected: (keyPointMatchesRatio) >= (minKeyPointMatchesRatio), actual: 0.598093 vs 0.69

$  ./opencv_test_features2d --gtest_filter=SIFT/DetectorScaleInvariance.*
...
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
...
scale = 1.5, keyPointMatchesRatio = 0.725973, scaleInliersRatio = 0.99606
scale = 2, keyPointMatchesRatio = 0.769883, scaleInliersRatio = 0.998623
/home/yosshi999_for_entry/opencv/modules/features2d/test/test_detectors_invariance.impl.hpp:198: Failure
Expected: (keyPointMatchesRatio) >= (minKeyPointMatchesRatio), actual: 0.598909 vs 0.69
```

**Comment by terfendail** [comment]
There could be some differences in AVX version of the code(e.g. different evaluation order or even something could be missed). Also AVX version of the code could(by design) fuse some multiplications and additions that actually increase accuracy of floating point evaluations but could decrease overall processing accuracy for some reason(that's why it so important to migrate to bit-exact).

**Comment by Yosshi999** [comment]
opencv_contrib used NORM_L1 for matching descriptors ([link](https://github.com/opencv/opencv_contrib/commit/1248735d1edd863e3b931fd6d0859720f11d3573#diff-a83c297681415e6f443f247c3498ce9bL833)) but the current master uses NORM_L2, which is SIFT's default ([link](https://github.com/opencv/opencv/blob/master/modules/features2d/test/test_descriptors_invariance.impl.hpp#L122)).

If it is changed to L1, the ratio increases (0.595092 -> 0.637014) but the test still fails.

**Comment by Yosshi999** [comment]
It seems that something wrong with `scaleKeyPoints`.
When I replace it with contrib-version, the test passes.

[opencv version](https://github.com/opencv/opencv/blob/master/modules/features2d/test/test_invariance_utils.hpp#L73): 
```
void scaleKeyPoints(const vector<KeyPoint>& src, vector<KeyPoint>& dst, float scale)
{
    dst.resize(src.size());
    for (size_t i = 0; i < src.size(); i++) {
        dst[i] = src[i];
        dst[i].pt.x *= scale;
        dst[i].pt.y *= scale;
        dst[i].size *= scale;
    }
}
```

[contirb version](https://github.com/opencv/opencv_contrib/blob/1248735d1edd863e3b931fd6d0859720f11d3573/modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp#L105):
```
void scaleKeyPoints(const vector<KeyPoint>& src, vector<KeyPoint>& dst, float scale)
{
    dst.resize(src.size());
    for(size_t i = 0; i < src.size(); i++)
        dst[i] = KeyPoint(src[i].pt.x * scale, src[i].pt.y * scale, src[i].size * scale, src[i].angle);
}
```

**Comment by Yosshi999** [comment]
~I think the move assignment in [Point2f](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/types.hpp#L1193) breaks something, but I'm not sure how to confirm it. 
Anyway I will replace it with contrib version in my PR.~ <- I made a mistake

the contrib version doesn't copy octave. I will investigate why we should drop these octaves to pass the test.

**Comment by Yosshi999** [comment]
Re-calculating octave and layer from kp.size may solve this problem..

**Comment by Yosshi999** [comment]
In the SIFT implementation, the equation
```
keypoint.size == sigma*powf(2.f, (layer + xi) / nOctaveLayers)*(1 << octave)*2
```
holds ([link](https://github.com/opencv/opencv/blob/master/modules/features2d/src/sift.simd.hpp#L400)), but
when keypoints are rescaled, only these sizes are changed and this relationship gets broken.
In this failure case, smaller size but the same octave causes the lack of gradient samples for descriptors. This is related to the reason why the opencv_contrib version works; all keypoints are put on octave=0 (original scale) and there are enough gradient samples for descriptors (however, its computational cost is higher than that of the opencv version).

So I implemented the calculation which finds the suitable octave and layer index of scaled keypoints.

DescriptorScaleInvariance test with `removeVerySmallKeypoints` and suitable octaves:
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SIFT/DescriptorScaleInvariance
[ RUN      ] SIFT/DescriptorScaleInvariance.scale/0, where GetParam() = ("detectors_descriptors_evaluation/images_datasets/bikes/img1.png", 0.78)
Keypoints: 3384
scale 1.5
scale = 1.5, inliers = 977, descInliersRatio = 0.998977
scale 2
scale = 2, inliers = 978, descInliersRatio = 1
scale 2.5
scale = 2.5, inliers = 975, descInliersRatio = 0.996933
[       OK ] SIFT/DescriptorScaleInvariance.scale/0 (734 ms)
[----------] 1 test from SIFT/DescriptorScaleInvariance (734 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (734 ms total)
[  PASSED  ] 1 test.
```

My PR will contain two features:
- call `removeVerySmallKeypoints` in detectors/descriptors invariance tests
- calculate suitable octave when `useProvidedKeypoints` is true in `SIFT_Impl::detectAndCompute`

**Comment by Yosshi999** [comment]
Sorry, I forgot the conversation in last week's meeting.
Will PR #2 and PR #4 be merged by you? Or should I re-create the PR which contains both #2 and #4 ?

**Comment by terfendail** [comment]
I think both PRs could be combined to the common branch(by either me or you) as soon as they will be ready to be merged. Afterwards this branch could be used as a base to create PR to main repository

**Comment by Yosshi999** [comment]
I rebased the pull request and squashed some commits.
https://github.com/Yosshi999/opencv/tree/gsoc_sift-better-test

If it is OK for you, I will send this PR to opencv/opencv and opencv/opencv_extra.

Now there are 3 commits in the PR. What I want to discuss is:
* Should I also squash these 3 commits? I wasn't able to come up with a suitable commit message for squashed one.
* The exact test will fail when AVX2 is disabled. Should I remove this commit?

**Comment by terfendail** [comment]
It's OK to make PR with 3 commits. Regarding exact test we could start with it included and remove it if there would be failures on CI related to this test

**Comment by Yosshi999** [comment]
👍  PR is here:
https://github.com/opencv/opencv/pull/17618
https://github.com/opencv/opencv_extra/pull/768
