### ISSUE TITLE
Converting SIFT to universal intrinsics.

### ISSUE THREAD

**Issue by terfendail** [terfendail/opencv#5]
[https://software.intel.com/sites/landingpage/IntrinsicsGuide/](https://software.intel.com/sites/landingpage/IntrinsicsGuide/) -description of what avx2 intrinsics intended for
[https://docs.opencv.org/master/df/d91/group__core__hal__intrin.html](https://docs.opencv.org/master/df/d91/group__core__hal__intrin.html) UI in opencv

opencv\modules\core\include\opencv2\core\hal\intrin_avx.hpp

and also intrin_cpp.hpp

https://github.com/opencv/opencv/pull/13631
https://github.com/opencv/opencv/pull/15180
https://github.com/opencv/opencv/pull/12784

**Comment by Yosshi999** [comment]
- use `#if CV_SIMD` without specific bitwidth (reference code: https://github.com/opencv/opencv/pull/13631)

**Comment by Yosshi999** [comment]
how to write bitwidth-agnostic simd code:
https://github.com/terfendail/opencv/blob/a202dc9a904961aa0021e6c9f71dcfbba06e6c1a/modules/imgproc/src/thresh.cpp#L207-L214
