### ISSUE TITLE
Parallel implementation of A-SIFT natively in C++, together with some regression test(s)

### ISSUE THREAD

**Issue by Yosshi999** [terfendail/opencv#7]
- [x] create regression tests for current python implementation
- [x] create performance tests for it
- [x] ~implement A-SIFT in C++~ integrate https://github.com/tlglovewf/ASIFT into opencv repository
- [ ] regression test, performance test, debugging

**Comment by terfendail** [comment]
Looks like there is an implementation of affine [detector](https://github.com/opencv/opencv/issues/4399#issuecomment-644489341). I haven't checked the code itself and results. More important I haven't checked whether the code is distributed under OpenCV compatible licence so unsure it could be used even partially. But it anyway exists and therefore could be a source of ideas to decide on what should or shouldn't be done

**Comment by Yosshi999** [comment]
It seems that the author has allowed integration.
https://github.com/tlglovewf/ASIFT/issues/1

**Comment by terfendail** [comment]
I'm going to discuss it with the OpenCV team. Looks like the most of source files contains BSD-like license and the author allowed to integrate the code. So probably it would be wiser to reuse the implementation and reduce the efforts spent. Anyway multi-feature affine detector idea seems reasonable.

**Comment by Yosshi999** [comment]
regression tests for current python implementation:
https://github.com/Yosshi999/opencv/commit/e783f130cf64169d6996d19c76aa8c42a7878923
https://github.com/Yosshi999/opencv_extra/commit/73778f08ccfaf646ea3ac8ee41ad03857f55052a

**Comment by Yosshi999** [comment]
https://github.com/Yosshi999/opencv/commit/a90bade7eff2d9d4161726598914e8427f46d6d1

The exact test wasn't passed. I'm investigating the reason.
